server:
  port: 8803
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    healthcheck:
      enabled: true
    refresh:
      enable: false
    prefer-same-zone-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}
    metadata-map:
      zone: zone1
security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://localhost:8002/oauth2/pub_key
