server:
  port: 8000
spring:
  cloud:
    config:
      server:
        git:
          uri: D:\GitHub\distributed-config-center
          timeout: 5
          search-paths: '{application}'
          force-pull: true