server:
  port: 9000
management:
  endpoint:
    health:
      show-details: always
zuul:
  prefix: /api
  ignored-services: '*'
  ignored-headers:
  routes:
    service1:
      path: /service1/**
      sensitiveHeaders:
      serviceId: service1
    service2: /service2/**
  force-original-query-string-encoding: true
  ribbon:
    eager-load:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    healthcheck:
      enabled: true
    refresh:
      enable: false
    prefer-same-zone-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}