server:
  port: 9000
management:
  endpoint:
    health:
      show-details: always
zuul:
  ignored-services: '*'
  routes:
    service1: /service1/**
    service2: /service2/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    healthcheck:
      enabled: true
    refresh:
      enable: false
    prefer-same-zone-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}