server:
  port: 8801
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    healthcheck:
      enabled: true
    refresh:
      enable: false
  instance:
    hostname: localhost
    prefer-ip-address: true